### ISSUE TITLE
Add it mplug script directory

### ISSUE THREAD

**Issue by z8512** [seanbreckenridge/mpvf#2]
Mplug is like a package manager but for mpv scripts.
Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by purarue** [comment]
Hmm -- not against it but trying to figure out how to do so, seems I'd make a PR to [this file](https://github.com/Nudin/mpv-script-directory/blob/master/mpv_script_directory.json)?

Also this is a shell script and I cant seem to find another example of that in the index, all of them are something else:

```
$ curl -s 'https://raw.githubusercontent.com/Nudin/mpv-script-directory/master/mpv_script_directory.json' | jq '.[].type' | tally
      3 "C plugin"
      3 "vapoursynth script"
      4 "other"
     12 "javascript"
     14 "user shader"
    208 "lua script"
```

But I guess I just use other and list in the scriptfiles -- not sure if it just supports putting a script on the users `$PATH`, which is all that this is -- its a script that calls `mpv` internally, not something `mpv` loads a plugin.

**Comment by z8512** [comment]
Apologies my mistake. I thought its a usual script which resides in ~/.config/mpv/scripts.
I think mpvf is like https://github.com/pystardust/ytfzf ? 
Do you have any idea about scripts like mpvf/ytfzf/ani-cli and friends? If yes, then please do open a pr

**Comment by purarue** [comment]
Yeah, this is pretty much like ytfzf, which [calls mpv internally](https://github.com/pystardust/ytfzf/blob/54d67d7965e425277102f1c48d73a52a46a8810b/ytfzf#L342).

I dont see ytfzf listed in the mpv-script-directory index, which I think it would be considering its popularity if it was something that mplug could install.

This is just like any other shell script, which is why I list the installation methods in the README (either just download/copy `mpvf` onto your `$PATH`), or use something like [basher](https://github.com/basherpm/basher):

```
basher install seanbreckenridge/mpvf
```

I dont see any scripts similar to this in the mplug index, so I dont think its meant to be used to install scripts like this.

**Comment by z8512** [comment]
Thank you
